spring:
  cloud:
    gateway:
#      globalcors:
#        cors-configurations:
#          "[/**]":
#            allowedOriginPatterns: "*"
#            allowedMethods:
#              - GET
#              - POST
#              - PATCH
#              - PUT
#              - DELETE
#              - OPTIONS

      routes:
        - id: auth
          uri: lb://ENTRYPOINT-SERVICE
          predicates:
            - Path=/entrypoint-service/**
          filters:
            - AuthFilter

        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer-service/**
          filters:
            - AuthFilter

        - id: workspace-service
          uri: lb://WORKSPACE-SERVICE
          predicates:
            - Path=/workspace-service/**
          filters:
            - AuthFilter