spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://ENTRYPOINT-SERVICE
          predicates:
            - Path=/entrypoint-service/**
          filters:
            - AuthFilter

        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer-service/**
          filters:
            - AuthFilter